version: '2'
services:
  d7legacy-mysql:
    container_name: d7legacy-mysql
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - /Users/kknopp/Sites/sites-databases/drupal-d7legacy:/var/lib/mysql
    networks:
      - dockercompose
    command: mysqld --max_allowed_packet=64M
    restart: always
  d7legacy:
    container_name: d7legacy
    image: codekoalas/drupal-legacy
    environment:
      VIRTUAL_HOST: .d7legacy.dev
      GIT_HOSTS: "10.170.3.208 gitlab.codekoalas.com"
      GIT_REPO: https://gitlab.codekoalas.com/dev-utilities/drupal7blank.git
      GIT_BRANCH: master
      MYSQL_SERVER: mysql
      MYSQL_DATABASE: drupal
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      DRUPAL_BASE_URL: http://d7legacy.dev
      DRUPAL_TRUSTED_HOSTS: d7legacy\.dev$$
      DRUPAL_HTTPS: "off"
      APACHE_DOCROOT: /var/www/site/docroot
      WWW: "false"
      PRODUCTION: "false"
      SESMailHub: mail-relay.ckdev.io
    volumes:
      - /Users/kknopp/Sites/sites-files/drupal-d7legacy:/mnt/sites-files
      - /Users/kknopp/Sites/drupal-d7legacy:/var/www/site
    networks:
      - dockercompose
    links:
      - d7legacy-mysql:mysql
    restart: always
networks:
  dockercompose:
    external:
      name: dockercompose_dockercompose
