version: '2'
services:
  d8blank-mysql:
    container_name: d8blank-mysql
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - /Users/kknopp/Sites/sites-databass/d8blank:/var/lib/mysql
    command: mysqld --max_allowed_packet=64M
    restart: always
  d8blank:
    container_name: d8blank
    image: codekoalas/drupal8
    environment:
      VIRTUAL_HOST: .d8blank.dev
      GIT_HOSTS: "10.170.3.208 gitlab.codekoalas.com"
      GIT_REPO: https://gitlab.codekoalas.com/dev-utilities/drupal8blank.git
      GIT_BRANCH: master
      MYSQL_SERVER: mysql
      MYSQL_DATABASE: drupal
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      DRUPAL_BASE_URL: http://d8blank.dev
      DRUPAL_TRUSTED_HOSTS: d8blank\.dev$$
      DRUPAL_HTTPS: "off"
      APACHE_DOCROOT: /var/www/site/docroot
      PRODUCTION: "false"
      SESMailHub: mail-relay.ckdev.io
      #LOCAL: "true"
    volumes:
      - /Users/kknopp/Sites/sites-files/d8blank:/mnt/sites-files
      - /Users/kknopp/Sites/d8blank:/var/www/site
    ports:
      - "9000:9000"
    links:
      - d8blank-mysql:mysql
    restart: always
