version: '2'
services:
  sample-node-site:
    container_name: sample-node-site
    image: codekoalas/nginx-node
    environment:
      VIRTUAL_HOST: .sample-node-site.dev
      GIT_REPO: https://gitlab.codekoalas.com/sites/sample-node-site.git
      GIT_BRANCH: master
      NODE_PREP: "npm run setup && npm run compile"
    restart: always
